servers:
    - url: ''
openapi: 3.0.3
info:
  description: API Description
  title: Email Classifier
  version: 1.0.0
  contact:
    email: qlekoane@solugrowth.com
  license:
    name: 'Huawei Cloud'
    url: 'http://www.solugrowth.com/licenses/LICENSE-2.0.html'
tags:
  - name: Qiniselani Lekoane
    description: Secured Admin-only calls
  - name: developers
    description: Operations available to regular SoluCloud developers
paths:
  /health-check:
    get:
      summary: 'Check if API is up and running'
      responses:
        default:
          description: Default response.
      parameters: []
   /predict:
     post:
       summary: 'Predict and Classify new email queries'
       responses:
        default:
          description: Default response.
      parameters: []
      requestBody:
        description: New Query Email Data
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email_id:
                type: number
                title: 'Unique Email Identifier'
                example:
                email_subject:
                type: string
                title: 'Subject Headline for Email'
                example:
                email_body:
                type: string
                title: 'Body Text of the Email'
                example:
                locations:
                type: string
                title: 'Locations array[l1,l2] Payload of the file/email'
                example:












